apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: artifacts.memez.de/stefftek/k8s-mongo-backup:1.1.0
            imagePullPolicy: IfNotPresent
            name: backup
          restartPolicy: OnFailure
  schedule: 0 * * * *
