apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: artifacts.memez.de/stefftek/k8s-mongo-backup
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure